[package]
name = "ptts-android"
version.workspace = true
edition = "2024"
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ptts = { workspace = true }
xn = { workspace = true }
rand = { workspace = true, default-features = false, features = ["std", "std_rng"] }
rand_distr = { workspace = true }
log = "0.4"
libc = { workspace = true }
rayon = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
android_logger = "0.14"
