fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    #[cfg(feature = "accelerate")]
    {
        println!("cargo:rustc-link-lib=framework=Accelerate");
    }
    #[cfg(feature = "cuda")]
    {
        println!("cargo:rerun-if-changed=src/compatibility.cuh");

        let builder = bindgen_cuda::Builder::default()
            .kernel_paths_glob("cuda-kernels/**/*.cu")
            .arg("--extended-lambda");
        println!("cargo:info={builder:?}");
        let bindings = builder.build_ptx().unwrap();
        bindings.write("src/cuda_backend/kernels.rs").unwrap();
    }
    #[cfg(feature = "vulkan")]
    build_vulkan_shaders();
}

/// Compile every `vulkan-kernels/*.comp` GLSL compute shader to SPIR-V using
/// `glslc` (from the Vulkan SDK / shaderc) and emit a generated module,
/// `$OUT_DIR/vulkan_shaders.rs`, exposing each shader as a `&[u32]` constant
/// named after the file (upper-cased, e.g. `arithmetic.comp` -> `ARITHMETIC`).
#[cfg(feature = "vulkan")]
fn build_vulkan_shaders() {
    use std::io::Write;
    use std::path::Path;

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let shader_dir = Path::new("vulkan-kernels");
    println!("cargo:rerun-if-changed=vulkan-kernels");

    let mut entries: Vec<_> = std::fs::read_dir(shader_dir)
        .expect("failed to read vulkan-kernels directory")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("comp"))
        .collect();
    entries.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs - do not edit\n");
    // Each shader is compiled twice: an f32 variant and an `-DUSE_F16` variant
    // (float16_t storage). The f16 variant needs a newer target-env for the
    // 16-bit-storage / float16 extensions.
    let variants = [("F32", "vulkan1.0", None), ("F16", "vulkan1.2", Some("USE_F16"))];
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().and_then(|s| s.to_str()).unwrap();
        let base = stem.to_uppercase().replace('-', "_");
        for (suffix, target, define) in &variants {
            let spv_path = Path::new(&out_dir).join(format!("{stem}_{suffix}.spv"));
            let mut cmd = std::process::Command::new("glslc");
            cmd.arg(format!("--target-env={target}")).arg("-O");
            if let Some(d) = define {
                cmd.arg(format!("-D{d}"));
            }
            let status = cmd
                .arg("-o")
                .arg(&spv_path)
                .arg(path)
                .status()
                .expect("failed to spawn glslc - is the Vulkan SDK / shaderc installed?");
            if !status.success() {
                panic!("glslc failed to compile {} ({suffix})", path.display());
            }
            generated.push_str(&format!(
                "pub static {base}_{suffix}: &[u8] = include_bytes!(r\"{}\");\n",
                spv_path.display()
            ));
        }
    }

    let dest = Path::new(&out_dir).join("vulkan_shaders.rs");
    let mut f = std::fs::File::create(&dest).expect("failed to create vulkan_shaders.rs");
    f.write_all(generated.as_bytes()).expect("failed to write vulkan_shaders.rs");
}
